servers:
# Jump Server
#  vars:
#    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@example.org"'
  hosts:
    vm-jump:
      ansible_host: vm-jump.example.org
      ansible_user: root
    vm-web:
      ansible_host: vm-web.example.org
      ansible_user: root
